name: Check comments
on:
  pull_request:
    types: [opened, synchronize]
  issue_comment:
    types: [created]

jobs:
  check_comments:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request
    outputs:
      test_trigger: ${{ steps.check.outputs.triggered }}
    steps:
      - uses: khan/pull-request-comment-trigger@master
        id: check
        with:
          trigger: '[run-tests]'

  tests:
    needs: [check_comments]
    if: ${{ needs.check_comments.outputs.test_trigger == 'true' }}
    uses: ./.github/workflows/ci-test.yml
