name: CI Test
on:
  issue_comment:
    types: [created]

jobs:
  tests:
    steps:
    runs-on: ubuntu-latest
    steps:
      - name: Execute tests
        if: github.event.issue.pull_request && contains(github.event.comment.body, '/test')
        run: 'echo "run unit tests"'

