name: CI Test
on:
  pull_request:
  issue_comment:
    types: [created]

jobs:
  tests:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/test')
    steps:
      - name: Execute tests
        run: 'echo "run unit tests"'

