name: CI Test
on:
  issue_comment:
    types: [created]

jobs:
  tests:
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/deploy')
    steps:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "run unit tests"'

