name: CI Test
on: workflow_call

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "run unit tests"'

  acceptance-tests:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "run acceptance tests"'
