name: CI Test
on:
  pull_request:
    types: [opened, synchronize]
  issue_comment:
    types: [created]

jobs:
  unit-tests:
    steps:
      - run: 'echo "run unit tests"'

  acceptance-tests:
    steps:
      - run: 'echo "run acceptance tests"'
